/:
    type: dynamic
    handler: null
    methods: ["get"]
^/test/.*(html|js|png|jpg)/?$:
    type: re
    handler: null
    methods: ["get", "post"]
/redirect:
    type: dynamic
    handler: null
    methods: ["get"]
