/:
    type: static
    handler: static/index.html
    methods: ["get"]
    headers:
        content-type: text/html; charset=UTF-8
/csrf-naive/:
    type: dynamic
    handler: null
    methods: ["get", "post"]
/csrf-token/:
    type: dynamic
    handler: null
    methods: ["get", "post"]
/origin-referer-protected/:
    type: dynamic
    handler: null
    methods: ["get", "post"]
/token-cors-protected/:
    type: dynamic
    handler: null
    methods: ["get", "post"]
    headers:
        Vary: Origin
/register/:
    type: dynamic
    handler: null
    methods: ["get", "post"]
/login/:
    type: dynamic
    handler: null
    methods: ["get", "post"]
