/:
    type: dynamic
    handler: null
    methods: ["get"]
^/static/(?!xss).*(html|js|png|jpg)/?$:
    type: re
    handler: null
    methods: ["get", "post"]
/redirect:
    type: dynamic
    handler: null
    methods: ["get"]
/xss/check:
    type: static
    handler: static/xss.js
    methods: ["get", "post", "put", "delete"]
    headers:
        Content-Type: text/javascript; charset=UTF-8